### ISSUE TITLE
Just tried and it's missing the AWS root cert.

### ISSUE THREAD

**Issue by nikshriv** [nikshriv/hass_navien_water_heater#12]
Just tried and it's missing the AWS root cert.

```
Logger: homeassistant.config_entries
Source: deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py:610 
First occurred: 7:24:02 AM (1 occurrences) 
Last logged: 7:24:02 AM

Error setting up entry navien for navien_water_heater
Traceback (most recent call last):
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 608, in tls_set
    f = open(ca_certs, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/config/custom_components/navien_water_heater/cert/AmazonRootCA1.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/var/lib/hass/custom_components/navien_water_heater/__init__.py", line 20, in async_setup_entry
    await navilink.start()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 49, in start
    await self.login()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 95, in login
    return await self._get_device_list()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 113, in _get_device_list
    await self._connect_aws_mqtt()
  File "/var/lib/hass/custom_components/navien_water_heater/navien_api.py", line 129, in _connect_aws_mqtt
    self.client.configureCredentials(self.aws_cert_path)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 246, in configureCredentials
    self._mqtt_core.configure_cert_credentials(cert_credentials_provider, cipher_provider)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 132, in configure_cert_credentials
    self._internal_async_client.set_cert_credentials_provider(cert_credentials_provider, ciphers_provider)
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 79, in set_cert_credentials_provider
    self._paho_client.tls_set(ca_certs=ca_path, cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_SSLv23,
  File "/var/lib/hass/deps/lib/python3.10/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 610, in tls_set
    raise IOError(ca_certs+": "+err.strerror)
OSError: /config/custom_components/navien_water_heater/cert/AmazonRootCA1.pem: No such file or directory
```

_Originally posted by @matkam in https://github.com/nikshriv/hass_navien_water_heater/issues/10#issuecomment-1455122233_

**Comment by nikshriv** [comment]
I'm guessing you manually installed the integration and didn't use HACs, right? You probably didn't copy the cert folder or the file inside of it. You need to put the AmazonRootCA1.pem file inside the cert folder. Just need to make sure you mirror the contents of the navien_water_heater folder exactly and it should work.

**Comment by matkam** [comment]
I installed it with HACs. And HASS is running via Docker compose. But I'll add the files manually as a workaround 👍

**Comment by nikshriv** [comment]
You’re right. I was having trouble getting a relative path to work, so I used an absolute path and never got around to figuring out how to get the relative path. I’ll look further into it and get it fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nikshriv** [comment]
This should be fixed with latest update. Please try it and let me know if it works for you now.
