### ISSUE TITLE
Issue Parsing Response Data

### ISSUE THREAD

**Issue by jkhalil** [nikshriv/hass_navien_water_heater#4]
After fresh install with latest updates there is an issue parsing data from the the API response:

Logger: homeassistant.config_entries
Source: custom_components/navien_water_heater/navien_api.py:387
Integration: Navien NaviLink Water Heater Integration ([documentation](https://www.github.com/nikshriv/hass_navien_water_heater))
First occurred: 4:24:49 PM (1 occurrences)
Last logged: 4:24:49 PM

`Error setting up entry Navian NaviLink for navien_water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/navien_water_heater/__init__.py", line 28, in async_setup_entry
    await navilink.connect()
  File "/config/custom_components/navien_water_heater/navien_api.py", line 239, in connect
    parsedResponse = self.parseResponse(data)
  File "/config/custom_components/navien_water_heater/navien_api.py", line 296, in parseResponse
    retval = self.parseChannelInformationResponse(commonResponseData, data)
  File "/config/custom_components/navien_water_heater/navien_api.py", line 387, in parseChannelInformationResponse
    struct.unpack(
struct.error: unpack requires a buffer of 15 bytes`

**Comment by nikshriv** [comment]
Making some changes under the hood and inadvertently changed the default repository to dev. Changing back now.

**Comment by jkhalil** [comment]
That fixed it. All good now. Thx for quick response.
